// import './components/image.js';
import './components/modalDestroy.js'
import './components/formValidation.js'
import './components/title.js'
import './components/header.js'
import './components/main.js'
import './components/crud.js'
import './components/menuHamburguer.js'
import './components/filterModal.js'
import './components/tableRecords.js'
import './components/form.js'
import './components/modalNotifiaction.js'
import './components/modalGallery.js'
import './components/uploadImage.js'
import './components/knm.js'
import './components/forms/formUsers.js'
import './components/tableRecordsUsers.js'
import './components/forms/formCustomers.js'
import './components/tableRecordsCustomers.js'
import './components/forms/formCompanies.js'
import './components/forms/formProducts.js'
import './components/page.js'
import './components/forms/formProductsCategory.js'
// import './components/modalErrors.js'
