// import './image.js';
import './modalDestroy.js'
import './formValidation.js'
import './title.js'
import './menuHamburguer.js'
import './filterModal.js'
import './tableRecords.js'
import './form.js'
import './modalNotifiaction.js'
import './modalGallery.js'
import './uploadImage.js'
import './knm.js'
import './formCustomers.js'
import './tableRecordsCustomers.js'
// import './modalErrors.js'
